// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.model.proto

package com.github.husky_demos.wallet_service.v1;

public final class WalletModel {
  private WalletModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:husky_demos.wallet_service.v1.Id)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code husky_demos.wallet_service.v1.Id}
   */
  public static final class Id extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:husky_demos.wallet_service.v1.Id)
      IdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Id.newBuilder() to construct.
    private Id(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Id() {
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Id();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Id(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.husky_demos.wallet_service.v1.WalletModel.internal_static_husky_demos_wallet_service_v1_Id_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.husky_demos.wallet_service.v1.WalletModel.internal_static_husky_demos_wallet_service_v1_Id_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.husky_demos.wallet_service.v1.WalletModel.Id.class, com.github.husky_demos.wallet_service.v1.WalletModel.Id.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.husky_demos.wallet_service.v1.WalletModel.Id)) {
        return super.equals(obj);
      }
      com.github.husky_demos.wallet_service.v1.WalletModel.Id other = (com.github.husky_demos.wallet_service.v1.WalletModel.Id) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.husky_demos.wallet_service.v1.WalletModel.Id prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code husky_demos.wallet_service.v1.Id}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:husky_demos.wallet_service.v1.Id)
        com.github.husky_demos.wallet_service.v1.WalletModel.IdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.husky_demos.wallet_service.v1.WalletModel.internal_static_husky_demos_wallet_service_v1_Id_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.husky_demos.wallet_service.v1.WalletModel.internal_static_husky_demos_wallet_service_v1_Id_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.husky_demos.wallet_service.v1.WalletModel.Id.class, com.github.husky_demos.wallet_service.v1.WalletModel.Id.Builder.class);
      }

      // Construct using com.github.husky_demos.wallet_service.v1.WalletModel.Id.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.husky_demos.wallet_service.v1.WalletModel.internal_static_husky_demos_wallet_service_v1_Id_descriptor;
      }

      @java.lang.Override
      public com.github.husky_demos.wallet_service.v1.WalletModel.Id getDefaultInstanceForType() {
        return com.github.husky_demos.wallet_service.v1.WalletModel.Id.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.husky_demos.wallet_service.v1.WalletModel.Id build() {
        com.github.husky_demos.wallet_service.v1.WalletModel.Id result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.husky_demos.wallet_service.v1.WalletModel.Id buildPartial() {
        com.github.husky_demos.wallet_service.v1.WalletModel.Id result = new com.github.husky_demos.wallet_service.v1.WalletModel.Id(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.husky_demos.wallet_service.v1.WalletModel.Id) {
          return mergeFrom((com.github.husky_demos.wallet_service.v1.WalletModel.Id)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.husky_demos.wallet_service.v1.WalletModel.Id other) {
        if (other == com.github.husky_demos.wallet_service.v1.WalletModel.Id.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.husky_demos.wallet_service.v1.WalletModel.Id parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.husky_demos.wallet_service.v1.WalletModel.Id) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:husky_demos.wallet_service.v1.Id)
    }

    // @@protoc_insertion_point(class_scope:husky_demos.wallet_service.v1.Id)
    private static final com.github.husky_demos.wallet_service.v1.WalletModel.Id DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.husky_demos.wallet_service.v1.WalletModel.Id();
    }

    public static com.github.husky_demos.wallet_service.v1.WalletModel.Id getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Id>
        PARSER = new com.google.protobuf.AbstractParser<Id>() {
      @java.lang.Override
      public Id parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Id(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Id> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Id> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.husky_demos.wallet_service.v1.WalletModel.Id getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WalletOrBuilder extends
      // @@protoc_insertion_point(interface_extends:husky_demos.wallet_service.v1.Wallet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string userId = 2;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 2;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string coinTypeId = 3;</code>
     * @return The coinTypeId.
     */
    java.lang.String getCoinTypeId();
    /**
     * <code>string coinTypeId = 3;</code>
     * @return The bytes for coinTypeId.
     */
    com.google.protobuf.ByteString
        getCoinTypeIdBytes();

    /**
     * <code>double availableBalance = 4;</code>
     * @return The availableBalance.
     */
    double getAvailableBalance();

    /**
     * <code>double freezeBalance = 5;</code>
     * @return The freezeBalance.
     */
    double getFreezeBalance();

    /**
     * <code>bool isLocking = 6;</code>
     * @return The isLocking.
     */
    boolean getIsLocking();
  }
  /**
   * Protobuf type {@code husky_demos.wallet_service.v1.Wallet}
   */
  public static final class Wallet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:husky_demos.wallet_service.v1.Wallet)
      WalletOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Wallet.newBuilder() to construct.
    private Wallet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Wallet() {
      id_ = "";
      userId_ = "";
      coinTypeId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Wallet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Wallet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              coinTypeId_ = s;
              break;
            }
            case 33: {

              availableBalance_ = input.readDouble();
              break;
            }
            case 41: {

              freezeBalance_ = input.readDouble();
              break;
            }
            case 48: {

              isLocking_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.husky_demos.wallet_service.v1.WalletModel.internal_static_husky_demos_wallet_service_v1_Wallet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.husky_demos.wallet_service.v1.WalletModel.internal_static_husky_demos_wallet_service_v1_Wallet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.husky_demos.wallet_service.v1.WalletModel.Wallet.class, com.github.husky_demos.wallet_service.v1.WalletModel.Wallet.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 2;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COINTYPEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object coinTypeId_;
    /**
     * <code>string coinTypeId = 3;</code>
     * @return The coinTypeId.
     */
    @java.lang.Override
    public java.lang.String getCoinTypeId() {
      java.lang.Object ref = coinTypeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        coinTypeId_ = s;
        return s;
      }
    }
    /**
     * <code>string coinTypeId = 3;</code>
     * @return The bytes for coinTypeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCoinTypeIdBytes() {
      java.lang.Object ref = coinTypeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coinTypeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVAILABLEBALANCE_FIELD_NUMBER = 4;
    private double availableBalance_;
    /**
     * <code>double availableBalance = 4;</code>
     * @return The availableBalance.
     */
    @java.lang.Override
    public double getAvailableBalance() {
      return availableBalance_;
    }

    public static final int FREEZEBALANCE_FIELD_NUMBER = 5;
    private double freezeBalance_;
    /**
     * <code>double freezeBalance = 5;</code>
     * @return The freezeBalance.
     */
    @java.lang.Override
    public double getFreezeBalance() {
      return freezeBalance_;
    }

    public static final int ISLOCKING_FIELD_NUMBER = 6;
    private boolean isLocking_;
    /**
     * <code>bool isLocking = 6;</code>
     * @return The isLocking.
     */
    @java.lang.Override
    public boolean getIsLocking() {
      return isLocking_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(coinTypeId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, coinTypeId_);
      }
      if (java.lang.Double.doubleToRawLongBits(availableBalance_) != 0) {
        output.writeDouble(4, availableBalance_);
      }
      if (java.lang.Double.doubleToRawLongBits(freezeBalance_) != 0) {
        output.writeDouble(5, freezeBalance_);
      }
      if (isLocking_ != false) {
        output.writeBool(6, isLocking_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(coinTypeId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, coinTypeId_);
      }
      if (java.lang.Double.doubleToRawLongBits(availableBalance_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, availableBalance_);
      }
      if (java.lang.Double.doubleToRawLongBits(freezeBalance_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, freezeBalance_);
      }
      if (isLocking_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isLocking_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.husky_demos.wallet_service.v1.WalletModel.Wallet)) {
        return super.equals(obj);
      }
      com.github.husky_demos.wallet_service.v1.WalletModel.Wallet other = (com.github.husky_demos.wallet_service.v1.WalletModel.Wallet) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getCoinTypeId()
          .equals(other.getCoinTypeId())) return false;
      if (java.lang.Double.doubleToLongBits(getAvailableBalance())
          != java.lang.Double.doubleToLongBits(
              other.getAvailableBalance())) return false;
      if (java.lang.Double.doubleToLongBits(getFreezeBalance())
          != java.lang.Double.doubleToLongBits(
              other.getFreezeBalance())) return false;
      if (getIsLocking()
          != other.getIsLocking()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + COINTYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getCoinTypeId().hashCode();
      hash = (37 * hash) + AVAILABLEBALANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAvailableBalance()));
      hash = (37 * hash) + FREEZEBALANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getFreezeBalance()));
      hash = (37 * hash) + ISLOCKING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLocking());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.husky_demos.wallet_service.v1.WalletModel.Wallet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code husky_demos.wallet_service.v1.Wallet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:husky_demos.wallet_service.v1.Wallet)
        com.github.husky_demos.wallet_service.v1.WalletModel.WalletOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.husky_demos.wallet_service.v1.WalletModel.internal_static_husky_demos_wallet_service_v1_Wallet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.husky_demos.wallet_service.v1.WalletModel.internal_static_husky_demos_wallet_service_v1_Wallet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.husky_demos.wallet_service.v1.WalletModel.Wallet.class, com.github.husky_demos.wallet_service.v1.WalletModel.Wallet.Builder.class);
      }

      // Construct using com.github.husky_demos.wallet_service.v1.WalletModel.Wallet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        userId_ = "";

        coinTypeId_ = "";

        availableBalance_ = 0D;

        freezeBalance_ = 0D;

        isLocking_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.husky_demos.wallet_service.v1.WalletModel.internal_static_husky_demos_wallet_service_v1_Wallet_descriptor;
      }

      @java.lang.Override
      public com.github.husky_demos.wallet_service.v1.WalletModel.Wallet getDefaultInstanceForType() {
        return com.github.husky_demos.wallet_service.v1.WalletModel.Wallet.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.husky_demos.wallet_service.v1.WalletModel.Wallet build() {
        com.github.husky_demos.wallet_service.v1.WalletModel.Wallet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.husky_demos.wallet_service.v1.WalletModel.Wallet buildPartial() {
        com.github.husky_demos.wallet_service.v1.WalletModel.Wallet result = new com.github.husky_demos.wallet_service.v1.WalletModel.Wallet(this);
        result.id_ = id_;
        result.userId_ = userId_;
        result.coinTypeId_ = coinTypeId_;
        result.availableBalance_ = availableBalance_;
        result.freezeBalance_ = freezeBalance_;
        result.isLocking_ = isLocking_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.husky_demos.wallet_service.v1.WalletModel.Wallet) {
          return mergeFrom((com.github.husky_demos.wallet_service.v1.WalletModel.Wallet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.husky_demos.wallet_service.v1.WalletModel.Wallet other) {
        if (other == com.github.husky_demos.wallet_service.v1.WalletModel.Wallet.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getCoinTypeId().isEmpty()) {
          coinTypeId_ = other.coinTypeId_;
          onChanged();
        }
        if (other.getAvailableBalance() != 0D) {
          setAvailableBalance(other.getAvailableBalance());
        }
        if (other.getFreezeBalance() != 0D) {
          setFreezeBalance(other.getFreezeBalance());
        }
        if (other.getIsLocking() != false) {
          setIsLocking(other.getIsLocking());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.husky_demos.wallet_service.v1.WalletModel.Wallet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.husky_demos.wallet_service.v1.WalletModel.Wallet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 2;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 2;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 2;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object coinTypeId_ = "";
      /**
       * <code>string coinTypeId = 3;</code>
       * @return The coinTypeId.
       */
      public java.lang.String getCoinTypeId() {
        java.lang.Object ref = coinTypeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          coinTypeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string coinTypeId = 3;</code>
       * @return The bytes for coinTypeId.
       */
      public com.google.protobuf.ByteString
          getCoinTypeIdBytes() {
        java.lang.Object ref = coinTypeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          coinTypeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string coinTypeId = 3;</code>
       * @param value The coinTypeId to set.
       * @return This builder for chaining.
       */
      public Builder setCoinTypeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        coinTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string coinTypeId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCoinTypeId() {
        
        coinTypeId_ = getDefaultInstance().getCoinTypeId();
        onChanged();
        return this;
      }
      /**
       * <code>string coinTypeId = 3;</code>
       * @param value The bytes for coinTypeId to set.
       * @return This builder for chaining.
       */
      public Builder setCoinTypeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        coinTypeId_ = value;
        onChanged();
        return this;
      }

      private double availableBalance_ ;
      /**
       * <code>double availableBalance = 4;</code>
       * @return The availableBalance.
       */
      @java.lang.Override
      public double getAvailableBalance() {
        return availableBalance_;
      }
      /**
       * <code>double availableBalance = 4;</code>
       * @param value The availableBalance to set.
       * @return This builder for chaining.
       */
      public Builder setAvailableBalance(double value) {
        
        availableBalance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double availableBalance = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvailableBalance() {
        
        availableBalance_ = 0D;
        onChanged();
        return this;
      }

      private double freezeBalance_ ;
      /**
       * <code>double freezeBalance = 5;</code>
       * @return The freezeBalance.
       */
      @java.lang.Override
      public double getFreezeBalance() {
        return freezeBalance_;
      }
      /**
       * <code>double freezeBalance = 5;</code>
       * @param value The freezeBalance to set.
       * @return This builder for chaining.
       */
      public Builder setFreezeBalance(double value) {
        
        freezeBalance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double freezeBalance = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFreezeBalance() {
        
        freezeBalance_ = 0D;
        onChanged();
        return this;
      }

      private boolean isLocking_ ;
      /**
       * <code>bool isLocking = 6;</code>
       * @return The isLocking.
       */
      @java.lang.Override
      public boolean getIsLocking() {
        return isLocking_;
      }
      /**
       * <code>bool isLocking = 6;</code>
       * @param value The isLocking to set.
       * @return This builder for chaining.
       */
      public Builder setIsLocking(boolean value) {
        
        isLocking_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isLocking = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsLocking() {
        
        isLocking_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:husky_demos.wallet_service.v1.Wallet)
    }

    // @@protoc_insertion_point(class_scope:husky_demos.wallet_service.v1.Wallet)
    private static final com.github.husky_demos.wallet_service.v1.WalletModel.Wallet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.husky_demos.wallet_service.v1.WalletModel.Wallet();
    }

    public static com.github.husky_demos.wallet_service.v1.WalletModel.Wallet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Wallet>
        PARSER = new com.google.protobuf.AbstractParser<Wallet>() {
      @java.lang.Override
      public Wallet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Wallet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Wallet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Wallet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.husky_demos.wallet_service.v1.WalletModel.Wallet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_husky_demos_wallet_service_v1_Id_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_husky_demos_wallet_service_v1_Id_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_husky_demos_wallet_service_v1_Wallet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_husky_demos_wallet_service_v1_Wallet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022wallet.model.proto\022\035husky_demos.wallet" +
      "_service.v1\"\023\n\002Id\022\r\n\005value\030\001 \001(\t\"|\n\006Wall" +
      "et\022\n\n\002id\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\022\022\n\ncoinTy" +
      "peId\030\003 \001(\t\022\030\n\020availableBalance\030\004 \001(\001\022\025\n\r" +
      "freezeBalance\030\005 \001(\001\022\021\n\tisLocking\030\006 \001(\010BT" +
      "\n(com.github.husky_demos.wallet_service." +
      "v1Z(github.com/husky-demos/wallet-servic" +
      "e/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_husky_demos_wallet_service_v1_Id_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_husky_demos_wallet_service_v1_Id_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_husky_demos_wallet_service_v1_Id_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_husky_demos_wallet_service_v1_Wallet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_husky_demos_wallet_service_v1_Wallet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_husky_demos_wallet_service_v1_Wallet_descriptor,
        new java.lang.String[] { "Id", "UserId", "CoinTypeId", "AvailableBalance", "FreezeBalance", "IsLocking", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
