// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.service.proto

package com.github.husky_demos.wallet_service.v1;

public final class WalletServiceOuterClass {
  private WalletServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024wallet.service.proto\022\035husky_demos.wall" +
      "et_service.v1\032\022wallet.model.proto2l\n\rWal" +
      "letService\022[\n\rqueryByUserId\022!.husky_demo" +
      "s.wallet_service.v1.Id\032%.husky_demos.wal" +
      "let_service.v1.Wallet\"\000BT\n(com.github.hu" +
      "sky_demos.wallet_service.v1Z(github.com/" +
      "husky-demos/wallet-service/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.husky_demos.wallet_service.v1.WalletModel.getDescriptor(),
        });
    com.github.husky_demos.wallet_service.v1.WalletModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
