// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.model.proto

package com.github.husky_demos.user_service.v1;

public final class UserModel {
  private UserModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:husky_demos.user_service.v1.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string nickName = 2;</code>
     * @return The nickName.
     */
    java.lang.String getNickName();
    /**
     * <code>string nickName = 2;</code>
     * @return The bytes for nickName.
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <code>string loginName = 3;</code>
     * @return The loginName.
     */
    java.lang.String getLoginName();
    /**
     * <code>string loginName = 3;</code>
     * @return The bytes for loginName.
     */
    com.google.protobuf.ByteString
        getLoginNameBytes();

    /**
     * <code>string loginPass = 4;</code>
     * @return The loginPass.
     */
    java.lang.String getLoginPass();
    /**
     * <code>string loginPass = 4;</code>
     * @return The bytes for loginPass.
     */
    com.google.protobuf.ByteString
        getLoginPassBytes();

    /**
     * <code>bool isLocking = 5;</code>
     * @return The isLocking.
     */
    boolean getIsLocking();
  }
  /**
   * Protobuf type {@code husky_demos.user_service.v1.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:husky_demos.user_service.v1.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      id_ = "";
      nickName_ = "";
      loginName_ = "";
      loginPass_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nickName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              loginName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              loginPass_ = s;
              break;
            }
            case 40: {

              isLocking_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.husky_demos.user_service.v1.UserModel.User.class, com.github.husky_demos.user_service.v1.UserModel.User.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nickName_;
    /**
     * <code>string nickName = 2;</code>
     * @return The nickName.
     */
    @java.lang.Override
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      }
    }
    /**
     * <code>string nickName = 2;</code>
     * @return The bytes for nickName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGINNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object loginName_;
    /**
     * <code>string loginName = 3;</code>
     * @return The loginName.
     */
    @java.lang.Override
    public java.lang.String getLoginName() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginName_ = s;
        return s;
      }
    }
    /**
     * <code>string loginName = 3;</code>
     * @return The bytes for loginName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLoginNameBytes() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGINPASS_FIELD_NUMBER = 4;
    private volatile java.lang.Object loginPass_;
    /**
     * <code>string loginPass = 4;</code>
     * @return The loginPass.
     */
    @java.lang.Override
    public java.lang.String getLoginPass() {
      java.lang.Object ref = loginPass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginPass_ = s;
        return s;
      }
    }
    /**
     * <code>string loginPass = 4;</code>
     * @return The bytes for loginPass.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLoginPassBytes() {
      java.lang.Object ref = loginPass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginPass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISLOCKING_FIELD_NUMBER = 5;
    private boolean isLocking_;
    /**
     * <code>bool isLocking = 5;</code>
     * @return The isLocking.
     */
    @java.lang.Override
    public boolean getIsLocking() {
      return isLocking_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nickName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nickName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, loginName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginPass_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, loginPass_);
      }
      if (isLocking_ != false) {
        output.writeBool(5, isLocking_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nickName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nickName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, loginName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginPass_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, loginPass_);
      }
      if (isLocking_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isLocking_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.husky_demos.user_service.v1.UserModel.User)) {
        return super.equals(obj);
      }
      com.github.husky_demos.user_service.v1.UserModel.User other = (com.github.husky_demos.user_service.v1.UserModel.User) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getNickName()
          .equals(other.getNickName())) return false;
      if (!getLoginName()
          .equals(other.getLoginName())) return false;
      if (!getLoginPass()
          .equals(other.getLoginPass())) return false;
      if (getIsLocking()
          != other.getIsLocking()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (37 * hash) + LOGINNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLoginName().hashCode();
      hash = (37 * hash) + LOGINPASS_FIELD_NUMBER;
      hash = (53 * hash) + getLoginPass().hashCode();
      hash = (37 * hash) + ISLOCKING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLocking());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.husky_demos.user_service.v1.UserModel.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.husky_demos.user_service.v1.UserModel.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code husky_demos.user_service.v1.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:husky_demos.user_service.v1.User)
        com.github.husky_demos.user_service.v1.UserModel.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.husky_demos.user_service.v1.UserModel.User.class, com.github.husky_demos.user_service.v1.UserModel.User.Builder.class);
      }

      // Construct using com.github.husky_demos.user_service.v1.UserModel.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        nickName_ = "";

        loginName_ = "";

        loginPass_ = "";

        isLocking_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_User_descriptor;
      }

      @java.lang.Override
      public com.github.husky_demos.user_service.v1.UserModel.User getDefaultInstanceForType() {
        return com.github.husky_demos.user_service.v1.UserModel.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.husky_demos.user_service.v1.UserModel.User build() {
        com.github.husky_demos.user_service.v1.UserModel.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.husky_demos.user_service.v1.UserModel.User buildPartial() {
        com.github.husky_demos.user_service.v1.UserModel.User result = new com.github.husky_demos.user_service.v1.UserModel.User(this);
        result.id_ = id_;
        result.nickName_ = nickName_;
        result.loginName_ = loginName_;
        result.loginPass_ = loginPass_;
        result.isLocking_ = isLocking_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.husky_demos.user_service.v1.UserModel.User) {
          return mergeFrom((com.github.husky_demos.user_service.v1.UserModel.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.husky_demos.user_service.v1.UserModel.User other) {
        if (other == com.github.husky_demos.user_service.v1.UserModel.User.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        if (!other.getLoginName().isEmpty()) {
          loginName_ = other.loginName_;
          onChanged();
        }
        if (!other.getLoginPass().isEmpty()) {
          loginPass_ = other.loginPass_;
          onChanged();
        }
        if (other.getIsLocking() != false) {
          setIsLocking(other.getIsLocking());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.husky_demos.user_service.v1.UserModel.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.husky_demos.user_service.v1.UserModel.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickName_ = "";
      /**
       * <code>string nickName = 2;</code>
       * @return The nickName.
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nickName = 2;</code>
       * @return The bytes for nickName.
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickName = 2;</code>
       * @param value The nickName to set.
       * @return This builder for chaining.
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 2;</code>
       * @param value The bytes for nickName to set.
       * @return This builder for chaining.
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object loginName_ = "";
      /**
       * <code>string loginName = 3;</code>
       * @return The loginName.
       */
      public java.lang.String getLoginName() {
        java.lang.Object ref = loginName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loginName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string loginName = 3;</code>
       * @return The bytes for loginName.
       */
      public com.google.protobuf.ByteString
          getLoginNameBytes() {
        java.lang.Object ref = loginName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string loginName = 3;</code>
       * @param value The loginName to set.
       * @return This builder for chaining.
       */
      public Builder setLoginName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loginName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string loginName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoginName() {
        
        loginName_ = getDefaultInstance().getLoginName();
        onChanged();
        return this;
      }
      /**
       * <code>string loginName = 3;</code>
       * @param value The bytes for loginName to set.
       * @return This builder for chaining.
       */
      public Builder setLoginNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loginName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object loginPass_ = "";
      /**
       * <code>string loginPass = 4;</code>
       * @return The loginPass.
       */
      public java.lang.String getLoginPass() {
        java.lang.Object ref = loginPass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loginPass_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string loginPass = 4;</code>
       * @return The bytes for loginPass.
       */
      public com.google.protobuf.ByteString
          getLoginPassBytes() {
        java.lang.Object ref = loginPass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginPass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string loginPass = 4;</code>
       * @param value The loginPass to set.
       * @return This builder for chaining.
       */
      public Builder setLoginPass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loginPass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string loginPass = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoginPass() {
        
        loginPass_ = getDefaultInstance().getLoginPass();
        onChanged();
        return this;
      }
      /**
       * <code>string loginPass = 4;</code>
       * @param value The bytes for loginPass to set.
       * @return This builder for chaining.
       */
      public Builder setLoginPassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loginPass_ = value;
        onChanged();
        return this;
      }

      private boolean isLocking_ ;
      /**
       * <code>bool isLocking = 5;</code>
       * @return The isLocking.
       */
      @java.lang.Override
      public boolean getIsLocking() {
        return isLocking_;
      }
      /**
       * <code>bool isLocking = 5;</code>
       * @param value The isLocking to set.
       * @return This builder for chaining.
       */
      public Builder setIsLocking(boolean value) {
        
        isLocking_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isLocking = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsLocking() {
        
        isLocking_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:husky_demos.user_service.v1.User)
    }

    // @@protoc_insertion_point(class_scope:husky_demos.user_service.v1.User)
    private static final com.github.husky_demos.user_service.v1.UserModel.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.husky_demos.user_service.v1.UserModel.User();
    }

    public static com.github.husky_demos.user_service.v1.UserModel.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.husky_demos.user_service.v1.UserModel.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:husky_demos.user_service.v1.LoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string loginName = 1;</code>
     * @return The loginName.
     */
    java.lang.String getLoginName();
    /**
     * <code>string loginName = 1;</code>
     * @return The bytes for loginName.
     */
    com.google.protobuf.ByteString
        getLoginNameBytes();

    /**
     * <code>string loginPass = 2;</code>
     * @return The loginPass.
     */
    java.lang.String getLoginPass();
    /**
     * <code>string loginPass = 2;</code>
     * @return The bytes for loginPass.
     */
    com.google.protobuf.ByteString
        getLoginPassBytes();
  }
  /**
   * Protobuf type {@code husky_demos.user_service.v1.LoginRequest}
   */
  public static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:husky_demos.user_service.v1.LoginRequest)
      LoginRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRequest() {
      loginName_ = "";
      loginPass_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              loginName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              loginPass_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_LoginRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.husky_demos.user_service.v1.UserModel.LoginRequest.class, com.github.husky_demos.user_service.v1.UserModel.LoginRequest.Builder.class);
    }

    public static final int LOGINNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object loginName_;
    /**
     * <code>string loginName = 1;</code>
     * @return The loginName.
     */
    @java.lang.Override
    public java.lang.String getLoginName() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginName_ = s;
        return s;
      }
    }
    /**
     * <code>string loginName = 1;</code>
     * @return The bytes for loginName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLoginNameBytes() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGINPASS_FIELD_NUMBER = 2;
    private volatile java.lang.Object loginPass_;
    /**
     * <code>string loginPass = 2;</code>
     * @return The loginPass.
     */
    @java.lang.Override
    public java.lang.String getLoginPass() {
      java.lang.Object ref = loginPass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginPass_ = s;
        return s;
      }
    }
    /**
     * <code>string loginPass = 2;</code>
     * @return The bytes for loginPass.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLoginPassBytes() {
      java.lang.Object ref = loginPass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginPass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, loginName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginPass_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginPass_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, loginName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginPass_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginPass_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.husky_demos.user_service.v1.UserModel.LoginRequest)) {
        return super.equals(obj);
      }
      com.github.husky_demos.user_service.v1.UserModel.LoginRequest other = (com.github.husky_demos.user_service.v1.UserModel.LoginRequest) obj;

      if (!getLoginName()
          .equals(other.getLoginName())) return false;
      if (!getLoginPass()
          .equals(other.getLoginPass())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOGINNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLoginName().hashCode();
      hash = (37 * hash) + LOGINPASS_FIELD_NUMBER;
      hash = (53 * hash) + getLoginPass().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.husky_demos.user_service.v1.UserModel.LoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code husky_demos.user_service.v1.LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:husky_demos.user_service.v1.LoginRequest)
        com.github.husky_demos.user_service.v1.UserModel.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_LoginRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.husky_demos.user_service.v1.UserModel.LoginRequest.class, com.github.husky_demos.user_service.v1.UserModel.LoginRequest.Builder.class);
      }

      // Construct using com.github.husky_demos.user_service.v1.UserModel.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        loginName_ = "";

        loginPass_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_LoginRequest_descriptor;
      }

      @java.lang.Override
      public com.github.husky_demos.user_service.v1.UserModel.LoginRequest getDefaultInstanceForType() {
        return com.github.husky_demos.user_service.v1.UserModel.LoginRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.husky_demos.user_service.v1.UserModel.LoginRequest build() {
        com.github.husky_demos.user_service.v1.UserModel.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.husky_demos.user_service.v1.UserModel.LoginRequest buildPartial() {
        com.github.husky_demos.user_service.v1.UserModel.LoginRequest result = new com.github.husky_demos.user_service.v1.UserModel.LoginRequest(this);
        result.loginName_ = loginName_;
        result.loginPass_ = loginPass_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.husky_demos.user_service.v1.UserModel.LoginRequest) {
          return mergeFrom((com.github.husky_demos.user_service.v1.UserModel.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.husky_demos.user_service.v1.UserModel.LoginRequest other) {
        if (other == com.github.husky_demos.user_service.v1.UserModel.LoginRequest.getDefaultInstance()) return this;
        if (!other.getLoginName().isEmpty()) {
          loginName_ = other.loginName_;
          onChanged();
        }
        if (!other.getLoginPass().isEmpty()) {
          loginPass_ = other.loginPass_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.husky_demos.user_service.v1.UserModel.LoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.husky_demos.user_service.v1.UserModel.LoginRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object loginName_ = "";
      /**
       * <code>string loginName = 1;</code>
       * @return The loginName.
       */
      public java.lang.String getLoginName() {
        java.lang.Object ref = loginName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loginName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string loginName = 1;</code>
       * @return The bytes for loginName.
       */
      public com.google.protobuf.ByteString
          getLoginNameBytes() {
        java.lang.Object ref = loginName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string loginName = 1;</code>
       * @param value The loginName to set.
       * @return This builder for chaining.
       */
      public Builder setLoginName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loginName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string loginName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoginName() {
        
        loginName_ = getDefaultInstance().getLoginName();
        onChanged();
        return this;
      }
      /**
       * <code>string loginName = 1;</code>
       * @param value The bytes for loginName to set.
       * @return This builder for chaining.
       */
      public Builder setLoginNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loginName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object loginPass_ = "";
      /**
       * <code>string loginPass = 2;</code>
       * @return The loginPass.
       */
      public java.lang.String getLoginPass() {
        java.lang.Object ref = loginPass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loginPass_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string loginPass = 2;</code>
       * @return The bytes for loginPass.
       */
      public com.google.protobuf.ByteString
          getLoginPassBytes() {
        java.lang.Object ref = loginPass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginPass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string loginPass = 2;</code>
       * @param value The loginPass to set.
       * @return This builder for chaining.
       */
      public Builder setLoginPass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loginPass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string loginPass = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoginPass() {
        
        loginPass_ = getDefaultInstance().getLoginPass();
        onChanged();
        return this;
      }
      /**
       * <code>string loginPass = 2;</code>
       * @param value The bytes for loginPass to set.
       * @return This builder for chaining.
       */
      public Builder setLoginPassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loginPass_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:husky_demos.user_service.v1.LoginRequest)
    }

    // @@protoc_insertion_point(class_scope:husky_demos.user_service.v1.LoginRequest)
    private static final com.github.husky_demos.user_service.v1.UserModel.LoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.husky_demos.user_service.v1.UserModel.LoginRequest();
    }

    public static com.github.husky_demos.user_service.v1.UserModel.LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
      @java.lang.Override
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.husky_demos.user_service.v1.UserModel.LoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:husky_demos.user_service.v1.LoginResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.husky_demos.user_service.v1.User user = 1;</code>
     * @return Whether the user field is set.
     */
    boolean hasUser();
    /**
     * <code>.husky_demos.user_service.v1.User user = 1;</code>
     * @return The user.
     */
    com.github.husky_demos.user_service.v1.UserModel.User getUser();
    /**
     * <code>.husky_demos.user_service.v1.User user = 1;</code>
     */
    com.github.husky_demos.user_service.v1.UserModel.UserOrBuilder getUserOrBuilder();

    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>int64 expireTime = 3;</code>
     * @return The expireTime.
     */
    long getExpireTime();
  }
  /**
   * Protobuf type {@code husky_demos.user_service.v1.LoginResult}
   */
  public static final class LoginResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:husky_demos.user_service.v1.LoginResult)
      LoginResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginResult.newBuilder() to construct.
    private LoginResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResult() {
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.github.husky_demos.user_service.v1.UserModel.User.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.github.husky_demos.user_service.v1.UserModel.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 24: {

              expireTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_LoginResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_LoginResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.husky_demos.user_service.v1.UserModel.LoginResult.class, com.github.husky_demos.user_service.v1.UserModel.LoginResult.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private com.github.husky_demos.user_service.v1.UserModel.User user_;
    /**
     * <code>.husky_demos.user_service.v1.User user = 1;</code>
     * @return Whether the user field is set.
     */
    @java.lang.Override
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.husky_demos.user_service.v1.User user = 1;</code>
     * @return The user.
     */
    @java.lang.Override
    public com.github.husky_demos.user_service.v1.UserModel.User getUser() {
      return user_ == null ? com.github.husky_demos.user_service.v1.UserModel.User.getDefaultInstance() : user_;
    }
    /**
     * <code>.husky_demos.user_service.v1.User user = 1;</code>
     */
    @java.lang.Override
    public com.github.husky_demos.user_service.v1.UserModel.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRETIME_FIELD_NUMBER = 3;
    private long expireTime_;
    /**
     * <code>int64 expireTime = 3;</code>
     * @return The expireTime.
     */
    @java.lang.Override
    public long getExpireTime() {
      return expireTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (expireTime_ != 0L) {
        output.writeInt64(3, expireTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (expireTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, expireTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.husky_demos.user_service.v1.UserModel.LoginResult)) {
        return super.equals(obj);
      }
      com.github.husky_demos.user_service.v1.UserModel.LoginResult other = (com.github.husky_demos.user_service.v1.UserModel.LoginResult) obj;

      if (hasUser() != other.hasUser()) return false;
      if (hasUser()) {
        if (!getUser()
            .equals(other.getUser())) return false;
      }
      if (!getToken()
          .equals(other.getToken())) return false;
      if (getExpireTime()
          != other.getExpireTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + EXPIRETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpireTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.husky_demos.user_service.v1.UserModel.LoginResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code husky_demos.user_service.v1.LoginResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:husky_demos.user_service.v1.LoginResult)
        com.github.husky_demos.user_service.v1.UserModel.LoginResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_LoginResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_LoginResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.husky_demos.user_service.v1.UserModel.LoginResult.class, com.github.husky_demos.user_service.v1.UserModel.LoginResult.Builder.class);
      }

      // Construct using com.github.husky_demos.user_service.v1.UserModel.LoginResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        token_ = "";

        expireTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.husky_demos.user_service.v1.UserModel.internal_static_husky_demos_user_service_v1_LoginResult_descriptor;
      }

      @java.lang.Override
      public com.github.husky_demos.user_service.v1.UserModel.LoginResult getDefaultInstanceForType() {
        return com.github.husky_demos.user_service.v1.UserModel.LoginResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.husky_demos.user_service.v1.UserModel.LoginResult build() {
        com.github.husky_demos.user_service.v1.UserModel.LoginResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.husky_demos.user_service.v1.UserModel.LoginResult buildPartial() {
        com.github.husky_demos.user_service.v1.UserModel.LoginResult result = new com.github.husky_demos.user_service.v1.UserModel.LoginResult(this);
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        result.token_ = token_;
        result.expireTime_ = expireTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.husky_demos.user_service.v1.UserModel.LoginResult) {
          return mergeFrom((com.github.husky_demos.user_service.v1.UserModel.LoginResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.husky_demos.user_service.v1.UserModel.LoginResult other) {
        if (other == com.github.husky_demos.user_service.v1.UserModel.LoginResult.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getExpireTime() != 0L) {
          setExpireTime(other.getExpireTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.husky_demos.user_service.v1.UserModel.LoginResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.husky_demos.user_service.v1.UserModel.LoginResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.github.husky_demos.user_service.v1.UserModel.User user_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.husky_demos.user_service.v1.UserModel.User, com.github.husky_demos.user_service.v1.UserModel.User.Builder, com.github.husky_demos.user_service.v1.UserModel.UserOrBuilder> userBuilder_;
      /**
       * <code>.husky_demos.user_service.v1.User user = 1;</code>
       * @return Whether the user field is set.
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.husky_demos.user_service.v1.User user = 1;</code>
       * @return The user.
       */
      public com.github.husky_demos.user_service.v1.UserModel.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? com.github.husky_demos.user_service.v1.UserModel.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.husky_demos.user_service.v1.User user = 1;</code>
       */
      public Builder setUser(com.github.husky_demos.user_service.v1.UserModel.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.husky_demos.user_service.v1.User user = 1;</code>
       */
      public Builder setUser(
          com.github.husky_demos.user_service.v1.UserModel.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.husky_demos.user_service.v1.User user = 1;</code>
       */
      public Builder mergeUser(com.github.husky_demos.user_service.v1.UserModel.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              com.github.husky_demos.user_service.v1.UserModel.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.husky_demos.user_service.v1.User user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.husky_demos.user_service.v1.User user = 1;</code>
       */
      public com.github.husky_demos.user_service.v1.UserModel.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.husky_demos.user_service.v1.User user = 1;</code>
       */
      public com.github.husky_demos.user_service.v1.UserModel.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              com.github.husky_demos.user_service.v1.UserModel.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.husky_demos.user_service.v1.User user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.husky_demos.user_service.v1.UserModel.User, com.github.husky_demos.user_service.v1.UserModel.User.Builder, com.github.husky_demos.user_service.v1.UserModel.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.husky_demos.user_service.v1.UserModel.User, com.github.husky_demos.user_service.v1.UserModel.User.Builder, com.github.husky_demos.user_service.v1.UserModel.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private long expireTime_ ;
      /**
       * <code>int64 expireTime = 3;</code>
       * @return The expireTime.
       */
      @java.lang.Override
      public long getExpireTime() {
        return expireTime_;
      }
      /**
       * <code>int64 expireTime = 3;</code>
       * @param value The expireTime to set.
       * @return This builder for chaining.
       */
      public Builder setExpireTime(long value) {
        
        expireTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 expireTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpireTime() {
        
        expireTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:husky_demos.user_service.v1.LoginResult)
    }

    // @@protoc_insertion_point(class_scope:husky_demos.user_service.v1.LoginResult)
    private static final com.github.husky_demos.user_service.v1.UserModel.LoginResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.husky_demos.user_service.v1.UserModel.LoginResult();
    }

    public static com.github.husky_demos.user_service.v1.UserModel.LoginResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResult>
        PARSER = new com.google.protobuf.AbstractParser<LoginResult>() {
      @java.lang.Override
      public LoginResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.husky_demos.user_service.v1.UserModel.LoginResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_husky_demos_user_service_v1_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_husky_demos_user_service_v1_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_husky_demos_user_service_v1_LoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_husky_demos_user_service_v1_LoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_husky_demos_user_service_v1_LoginResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_husky_demos_user_service_v1_LoginResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020user.model.proto\022\033husky_demos.user_ser" +
      "vice.v1\"]\n\004User\022\n\n\002id\030\001 \001(\t\022\020\n\010nickName\030" +
      "\002 \001(\t\022\021\n\tloginName\030\003 \001(\t\022\021\n\tloginPass\030\004 " +
      "\001(\t\022\021\n\tisLocking\030\005 \001(\010\"4\n\014LoginRequest\022\021" +
      "\n\tloginName\030\001 \001(\t\022\021\n\tloginPass\030\002 \001(\t\"a\n\013" +
      "LoginResult\022/\n\004user\030\001 \001(\0132!.husky_demos." +
      "user_service.v1.User\022\r\n\005token\030\002 \001(\t\022\022\n\ne" +
      "xpireTime\030\003 \001(\003BP\n&com.github.husky_demo" +
      "s.user_service.v1Z&github.com/husky-demo" +
      "s/user-service/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_husky_demos_user_service_v1_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_husky_demos_user_service_v1_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_husky_demos_user_service_v1_User_descriptor,
        new java.lang.String[] { "Id", "NickName", "LoginName", "LoginPass", "IsLocking", });
    internal_static_husky_demos_user_service_v1_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_husky_demos_user_service_v1_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_husky_demos_user_service_v1_LoginRequest_descriptor,
        new java.lang.String[] { "LoginName", "LoginPass", });
    internal_static_husky_demos_user_service_v1_LoginResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_husky_demos_user_service_v1_LoginResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_husky_demos_user_service_v1_LoginResult_descriptor,
        new java.lang.String[] { "User", "Token", "ExpireTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
